use mlua::{Lua, Result as LuaResult, Table};

pub const NSE_MODULES: &[&str] = &[
    "stdnse",
    "nmap",
    "http",
    "comm",
    "sslcert",
    "tls",
    "shortport",
    "socket",
    "ssh2",
    "ftp",
    "smtp",
    "mysql",
    "postgres",
    "pgsql",
    "mssql",
    "sybase",
    "redis",
    "mongodb",
    "ldap",
    "snmp",
    "smb",
    "rdp",
    "vnc",
    "ntp",
    "memcached",
    "imap",
    "pop3",
    "netbios",
    "oracle",
    "winrm",
    "radius",
    "dhcp",
    "dhcp6",
    "sip",
    "tftp",
    "upnp",
    "tns",
    "afp",
    "amqp",
    "ajp",
    "ncp",
    "ndmp",
    "nrpc",
    "citrixxml",
    "ospf",
    "asn1",
    "sasl",
    "slaxml",
    "re",
    "httpspider",
    "base64",
    "base32",
    "datetime",
    "rand",
    "url",
    "creds",
    "openssl",
    "pcre",
    "io",
    "os",
    "unittest",
    "target",
    "strbuf",
    "tab",
    "stringaux",
    "bin",
    "bit",
    "vulns",
    "unpwdb",
    "brute",
    "datafiles",
    "json",
    "ssh",
    "ssh1",
    "dns",
    "http2",
    "elasticsearch",
    "kafka",
    "mqtt",
    "websocket",
    "telnet",
    "sftp",
    "whois",
    "finger",
    "stun",
    "packet",
    "nsedebug",
    "strict",
    "geoip",
    "rpc",
    "smb2",
    "smbauth",
    "match",
    "sslv2",
    "msrpc",
    "ike",
    "ipp",
    "coap",
    "idna",
    "ipOps",
    "iax2",
    "drda",
    "eigrp",
    "giop",
    "iscsi",
    "jdwp",
    "rsync",
    "socks",
    "rtsp",
    "tn3270",
    "xmpp",
    "isns",
    "membase",
    "bitcoin",
    "bittorrent",
    "cassandra",
    "dicom",
    "knx",
    "multicast",
    "nbd",
    "natpmp",
    "proxy",
    "srvloc",
    "wsdd",
    "xdmcp",
    "bjnp",
    "cvs",
    "dnssd",
    "eap",
    "pppoe",
    "rpcap",
    "rmi",
    "ipmi",
    "irc",
    "versant",
    "omp2",
    "gps",
    "mobileme",
    "ls",
    "unicode",
    "lpeg",
    "lfs",
    "libssh2",
];

pub const STANDARD_SYNC_MODULES: &[&str] = &[
    "stdnse",
    "nmap",
    "http",
    "comm",
    "sslcert",
    "tls",
    "shortport",
    "socket",
    "ssh2",
    "ftp",
    "smtp",
    "mysql",
    "postgres",
    "pgsql",
    "mssql",
    "sybase",
    "redis",
    "mongodb",
    "ldap",
    "snmp",
    "smb",
    "rdp",
    "vnc",
    "ntp",
    "memcached",
    "imap",
    "pop3",
    "netbios",
    "oracle",
    "winrm",
    "radius",
    "dhcp",
    "finger",
    "whois",
    "sftp",
    "dns",
    "datafiles",
    "url",
    "json",
    "base64",
    "datetime",
    "rand",
    "string",
    "table",
];

pub fn setup_nse_globals(lua: &Lua) -> LuaResult<()> {
    let globals = lua.globals();

    for name in NSE_MODULES {
        globals.set(*name, lua.create_table()?)?;
    }

    globals.set("_REQUIRE_MODULES", lua.create_table()?)?;
    globals.set("_SCRIPT_OUTPUT", lua.create_table()?)?;

    Ok(())
}

pub fn sync_require_modules(lua: &Lua) -> LuaResult<()> {
    let globals = lua.globals();
    let modules = globals.get::<Table>("_REQUIRE_MODULES")?;

    for name in STANDARD_SYNC_MODULES {
        if let Ok(table) = globals.get::<Table>(*name) {
            let _ = modules.set(*name, table);
        }
    }

    Ok(())
}
