//! NSE output formatting module
//!
//! Provides various output format handlers compatible with nmap conventions.

use serde::{Deserialize, Serialize};
use std::fmt::Write as FmtWrite;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NseOutput {
    pub target: String,
    pub scripts: String,
    pub output: String,
    pub ports: Option<String>,
    pub timing: u8,
    pub debug: u8,
}

#[derive(Debug, Clone)]
pub enum OutputFormat {
    Stdout,
    Xml(String),
    Grepable(String),
    Normal(String),
    All,
}

/// Generate XML output in nmap format
pub fn generate_xml(results: &[NseOutput]) -> String {
    let mut xml = String::new();

    let _ = writeln!(xml, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    let _ = writeln!(
        xml,
        "<nmaprun scanner=\"eggsec\" args=\"eggsec nse\" start=\"{}\" version=\"1.0\">",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs()
    );

    let _ = writeln!(xml, "  <verbose level=\"0\"/>");
    let _ = writeln!(xml, "  <debugging level=\"0\"/>");

    for result in results {
        let _ = writeln!(
            xml,
            "  <host starttime=\"{}\" endtime=\"{}\">",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs()
                + 1
        );

        let _ = writeln!(xml, "    <status state=\"up\" reason=\"echo-reply\"/>");
        let _ = writeln!(
            xml,
            "    <address addr=\"{}\" addrtype=\"ipv4\"/>",
            result.target
        );

        let _ = writeln!(xml, "    <hostnames>");
        let _ = writeln!(
            xml,
            "      <hostname name=\"{}\" type=\"user\"/>",
            result.target
        );
        let _ = writeln!(xml, "    </hostnames>");

        let _ = writeln!(xml, "    <ports>");
        let port_line = result.ports.as_deref().unwrap_or("80/tcp   open  http");
        let port_id = port_line.split('/').next().unwrap_or("80");
        let _ = writeln!(xml, "      <port protocol=\"tcp\" portid=\"{}\">", port_id);
        let _ = writeln!(xml, "        <state state=\"open\" reason=\"syn-ack\"/>");
        let _ = writeln!(
            xml,
            "        <service name=\"http\" method=\"probed\" conf=\"10\"/>"
        );
        let _ = writeln!(
            xml,
            "        <script id=\"{}\" output=\"{}\">",
            escape_xml(&result.scripts),
            escape_xml(&result.output)
        );
        let _ = writeln!(xml, "        </script>");
        let _ = writeln!(xml, "      </port>");
        let _ = writeln!(xml, "    </ports>");

        let _ = writeln!(xml, "    <times srtt=\"0\" rttvar=\"0\" to=\"100000\"/>");
        let _ = writeln!(xml, "  </host>");
    }

    let _ = writeln!(xml, "  <runstats>");
    let _ = writeln!(xml, "    <finished elapsed=\"1\" exit=\"success\"/>");
    let _ = writeln!(
        xml,
        "    <hosts up=\"{}\" down=\"0\" total=\"{}\"/>",
        results.len(),
        results.len()
    );
    let _ = writeln!(xml, "  </runstats>");
    let _ = writeln!(xml, "</nmaprun>");

    xml
}

/// Generate grepable output in nmap -oG format
pub fn generate_grepable(results: &[NseOutput]) -> String {
    let mut output = String::new();

    let _ = writeln!(output, "# Nmap scan report generated by Eggsec");

    for result in results {
        let _ = writeln!(output, "Host: {} () Status: Up", result.target);
        let ports_str = result.ports.as_deref().unwrap_or("80/open/tcp//http///");
        let _ = writeln!(
            output,
            "Host: {} ()     Ports: {}",
            result.target, ports_str
        );

        let script_output = result.output.replace('\n', "\\n");
        let _ = writeln!(output, "| {}: {}", result.scripts, script_output);
    }

    let _ = writeln!(
        output,
        "# Scan done: {} IP address (1 host up) scanned in 0.01 seconds",
        results.len()
    );

    output
}

/// Generate normal output in nmap format
pub fn generate_normal(results: &[NseOutput]) -> String {
    let mut output = String::new();

    let _ = writeln!(
        output,
        "Starting Eggsec NSE scan at {}",
        chrono_lite_timestamp()
    );
    let _ = writeln!(
        output,
        "NSE Timing: About {}% done",
        (results.len() as f32 * 33.0).min(100.0)
    );
    let _ = writeln!(output);

    for result in results {
        let _ = writeln!(output, "Nmap scan report for {}", result.target);
        let _ = writeln!(output, "Host is up (0.0010s latency).");
        let _ = writeln!(output, "PORT     STATE SERVICE");
        let _ = write_ports(&mut output, result.ports.as_deref());

        let _ = writeln!(output, "| {}:", result.scripts);
        for line in result.output.lines() {
            let _ = writeln!(output, "|   {}", line);
        }

        let _ = writeln!(output);
    }

    let _ = writeln!(
        output,
        "Nmap done: {} IP address ({} host up) scanned",
        results.len(),
        results.len()
    );

    output
}

fn write_ports(output: &mut String, ports: Option<&str>) -> std::fmt::Result {
    match ports {
        Some(ports) => {
            for raw in ports.lines().map(str::trim).filter(|line| !line.is_empty()) {
                if raw.contains('/') {
                    writeln!(output, "{}", raw)?;
                } else {
                    writeln!(output, "{}/tcp   open  unknown", raw)?;
                }
            }
        }
        None => {
            writeln!(output, "80/tcp   open  http")?;
        }
    }
    Ok(())
}

fn escape_xml(s: &str) -> String {
    let mut escaped = String::new();
    for c in s.chars() {
        match c {
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '&' => escaped.push_str("&amp;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            _ => escaped.push(c),
        }
    }
    escaped
}

fn chrono_lite_timestamp() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    format!("{}", now.as_secs())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_xml_output() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("80".to_string()),
            timing: 3,
            debug: 0,
        }];

        let xml = generate_xml(&results);
        assert!(xml.contains("<?xml"));
        assert!(xml.contains("example.com"));
    }

    #[test]
    fn test_grepable_output() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("80".to_string()),
            timing: 3,
            debug: 0,
        }];

        let grepable = generate_grepable(&results);
        assert!(grepable.contains("example.com"));
    }

    #[test]
    fn test_normal_output() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("80".to_string()),
            timing: 3,
            debug: 0,
        }];

        let normal = generate_normal(&results);
        assert!(normal.contains("example.com"));
    }

    #[test]
    fn test_normal_output_uses_ports_field() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("443/tcp   open  https".to_string()),
            timing: 3,
            debug: 0,
        }];

        let normal = generate_normal(&results);
        assert!(normal.contains("443/tcp   open  https"));
        assert!(!normal.contains("80/tcp   open  http"));
    }
}
